#!/usr/bin/env bash

#defaults
COMMAND=
CLUSTER=
SERVICE=
VALUES=
IMAGE_TAG=
WORKING_DIR="deployment"
DEBUG="false"
PRUNE_TASK_DEFINITIONS=
TIMEOUT="300"
DRY_RUN="false"

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PATH="$PATH:$CURRENT_DIR/lib/bin:$PATH:$CURRENT_DIR/lib/ecs-deploy:$CURRENT_DIR/lib/gucci"

# functions

function show_usage() {
    cat << EOL
usage: $0 command [parameters]

command:
    update                  update remote task definition with given image tag
    install                 install local task definition (task-definition.json.tmpl), using given image tag

parameters:
    -h|--help               show this usage
    -v|--version            show version info
    -d|--debug              debug mode, verbose (default: $DEBUG)
    -c|--cluster value      ecs cluster (eg: cls01)
    -s|--service value      ecs service (eg: hello-world-dev)
    -t|--tag value          Docker image tag (eg: 1ab2c3-12)
    -w|--working-dir value  where to search for resources (default: $WORKING_DIR)
    -f|--values value       values file (eg: values-dev.yaml)
    --prune value           only keep given task definitions (eg: 5)
    --timeout value         timeout (default: $TIMEOUT)
    --dry-run               dry-run mode, avoid any deployment (default: $DRY_RUN)
EOL
}

function show_version() {
    [[ "$DEBUG" != "false" ]] && log "showing version"
    echo "(templating) gucci: $( gucci --version )"
    echo "(deployment) ecs-deploy: $( ecs-deploy --version )"
}

function log() {
    echo -e "[$( date "+%Y-%m-%d %H:%M:%S" )] $*"
}

function template_on() {
    local target="$1" ; shift
    [[ "$DEBUG" != "false" ]] && log "[template] executing ($# params): gucci $@"
    ( cd "$( realpath "$WORKING_DIR" )" ; gucci "$@" > "$target" )
}

function deployment_PATH() {
    echo "$WORKING_DIR/bin"
}

function init_values() {
    if [[ ! -z "$VALUES" ]]; then
        VALUES="$( realpath $WORKING_DIR/$VALUES )"
        log "values: $VALUES"
    fi
}

function init_resource() {
    local name="$1"
    local folder="$2"

    local script="$( echo $( resource_get $name ) | sed 's/.tmpl//g' )"
    realpath "$folder/$( resource_get $name )" > /dev/null 2>&1 \
        && resource_set "$( realpath $folder/$( resource_get $name ) )" "$name"

    if [[ -f "$( resource_get $name )" ]]; then
        log "(template) $name: $( resource_get $name )"
        [[ "$DEBUG" != "false" ]] && log "$( cat "$( resource_get $name )" )"

        local command_line=()
        local original_value="$( resource_get $name )"

        resource_set "/tmp/$script.$RANDOM" "$name"
        log "(current) $name: $( resource_get $name )"

        if [[ ! -z "$VALUES" ]]; then
            command_line+=("-f" "$VALUES")
        fi

        template_on "$( resource_get $name )" "${command_line[@]}" "$original_value" || {
            log "cannot prepare $name";
            exit 1;
        }
        [[ "$DEBUG" != "false" ]] && log "$( cat "$( resource_get $name )" )"

        chmod +x "$( resource_get $name )"
    fi
}

function flags_install() {
    local flags="--task-definition-file $TASK_DEFINITION"
    [[ -f $TASK_SET ]] && flags="$flags --task-set-file $TASK_SET"
    echo "$flags"
}

function flags_confirmation() {
    [[ -f $( resource_get LIFECYCLE_CONFIRMATION ) ]] \
        && echo "--canary-confirmation $( resource_get LIFECYCLE_CONFIRMATION )" \
        || echo "--canary-confirmation wait_timeout"
}

function resource_set() {
    local value=$1
    local key=$2
    eval "$key='$value'"   # 'declare -g' unsupported on bash < 4.2
}

function resource_get() {
    local key=$1
    echo "${!key}"
}

function do_initialize() {    
    # enrich PATH with shared and deployment binaries
    PATH="$CURRENT_DIR/bin/helpers:$PATH"
    realpath $( deployment_PATH ) > /dev/null 2>&1 && PATH="$( realpath $( deployment_PATH ) ):$PATH"

    [[ "$DEBUG" != "false" ]] && {
        log "PATH: $PATH";
        log "dry-run: $DRY_RUN"
    }

    # mandatory command
    [[ -z "$COMMAND" ]] && { echo "no command provided" ; show_usage ; exit 1; }
    [[ "$COMMAND" != "update" && "$COMMAND" != "install" ]] && { echo "unsupported command" ; show_usage ; exit 1; }
    
    # mandatory parameters
    [[ -z "$CLUSTER" ]] && { echo "no cluster provided" ; show_usage ; exit 1; }
    [[ -z "$SERVICE" ]] && { echo "no service provided" ; show_usage ; exit 1; }
    [[ -z "$IMAGE_TAG" ]] && { echo "no image provided" ; show_usage ; exit 1; }
    
    # shared initialization
    init_values
    init_resource LIFECYCLE_CONFIRMATION "$( deployment_PATH )"
    init_resource LIFECYCLE_POST "$( deployment_PATH )"
    
    # install-specific initialization
    if [[ "$COMMAND" == "install" ]]; then
      init_resource TASK_DEFINITION "$WORKING_DIR"
      init_resource TASK_SET "$WORKING_DIR"
    fi
}

function do_deploy() {
    local command_line=()
    [[ "$COMMAND" == "update" ]] && command_line=("-c" "$CLUSTER" "-n" "$SERVICE" "--tag-only" "$IMAGE_TAG" "-i" "ignored-image" $( flags_confirmation ) "--timeout" "$TIMEOUT")
    [[ "$COMMAND" == "install" ]] && command_line=("-c" "$CLUSTER" "-n" "$SERVICE" "--tag-only" "$IMAGE_TAG" "-i" "ignored-image" $( flags_install ) $( flags_confirmation ) "--timeout" "$TIMEOUT")
    [[ ! -z "$PRUNE_TASK_DEFINITIONS" ]] && command_line+=("--max-definitions" "$PRUNE_TASK_DEFINITIONS")
    [[ "$DRY_RUN" != "false" ]] && command_line+=("--dry-run")
    [[ "$DEBUG" != "false" ]] && command_line+=("--verbose")

    [[ "$DEBUG" != "false" ]] && log "[deploy] executing (${#command_line[@]} params): ecs-deploy ${command_line[@]}"
    ecs-deploy ${command_line[@]}
}

function on_post_deploy() {
    local action="$( resource_get LIFECYCLE_POST )"
    if [[ -f "$action" ]]; then
        [[ "$DEBUG" != "false" ]] && log "[post-deploy] executing $action";
        execute $action
    else
        [[ "$DEBUG" != "false" ]] && log "[post-deploy] skipping, not set";
    fi
    return 0
}

function execute() {
    local command_line=$*
    [[ "$DRY_RUN" != "false" ]] && log "dry-run, skipping $command_line" || $command_line
}

# skip when sourcing the script
if [ "$0" = "$BASH_SOURCE" ] ; then

    resource_set task-definition.json.tmpl TASK_DEFINITION
    resource_set task-set.json.tmpl TASK_SET
    resource_set confirm.sh.tmpl LIFECYCLE_CONFIRMATION
    resource_set post.sh.tmpl LIFECYCLE_POST

    # main
    "$CURRENT_DIR"/bin/install --app

    [[ $# -eq 0 ]] && show_usage && exit 1
    while [[ $# -gt 0 ]]; do
        key="$1"
        case $key in
            -w|--working-dir)
            WORKING_DIR="$2"
            shift 2
            ;;
            -c|--cluster)
            CLUSTER="$2"
            shift 2
            ;;
            -s|--service)
            SERVICE="$2"
            shift 2
            ;;
            -t|--tag)
            IMAGE_TAG="$2"
            shift 2
            ;;
            -f|--values)
            VALUES="$2"
            shift 2
            ;;
            --prune)
            PRUNE_TASK_DEFINITIONS="$2"
            shift 2
            ;;
            --timeout)
            TIMEOUT="$2"
            shift 2
            ;;
            -d|--debug)
            DEBUG="true"
            shift 1
            ;;
            --dry-run)
            DRY_RUN="true"
            shift 1
            ;;
            -v|--version)
            show_version ; exit 0
            ;;
            -h|--help)
            show_usage ; exit 0
            ;;
            -*|--*)
            show_usage ; exit 1
            ;;
            *)
            COMMAND="$1"
            shift 1
            ;;
        esac
    done

    do_initialize
    do_deploy
    
    on_post_deploy
fi