name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dist
        run: ./dist.sh

      - name: Run bash script
        shell: bash
        run: |
            echo "#!/usr/bin/env bash" > dist/install.sh
            echo "echo Downloading release ${{ github.ref_name }}" >> dist/install.sh
            echo "curl -L https://github.com/GuccioGucci/yoke/releases/download/${{ github.ref_name }}/yoke.tar.gz | tar -xz" >> dist/install.sh
            echo "echo Done" >> dist/install.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
              dist/yoke.bin
              dist/yoke.tar.gz
              dist/install.sh